#!/usr/bin/with-contenv bash
# ==============================================================================
# Start universal-silabs-flasher if requested
# ==============================================================================
source /etc/bashlog/log.sh;

declare device
declare baudrate
declare firmware

device=$DEVICE
baudrate=$BAUDRATE
firmware=$FIRMWARE

if [ $AUTOFLASH_FIRMWARE -eq 0 ]; then
    log 'info' "Flashing firmware is disabled"
    exit 0
fi

if [[ -z "${FIRMWARE}" ]]; then
    log 'info' "No firmware found for the selected device, assuming firmware is installed."
    exit 0
fi

# All firmware we flash have a known baudrate of 460800, let cpcd know.
echo 460800 > /tmp/known-baudrate

log 'info' "Starting universal-silabs-flasher with ${device} (baudrate ${baudrate})"
exec universal-silabs-flasher --device ${device} \
     flash --ensure-exact-version --allow-cross-flashing --firmware "/root/firmware/${firmware}"