#!/usr/bin/with-contenv bash
# ==============================================================================
# Start EmberZNet Zigbee Daemon
# ==============================================================================
source /etc/bashlog/log.sh;

mkdir -p /data/zigbeed && cd /data/zigbeed || log 'error' "Could not change to zigbeed working directory"

log 'info' "Starting zigbeed..."
exec /usr/local/bin/zigbeed --radio-url "spinel+cpc://cpcd_0?iid=1&iid-list=0" \
                           --ezsp-listen "::" \
                           --ezsp-listen-port ${EZSP_LISTEN_PORT}
