#!/usr/bin/with-contenv bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
source /etc/bashlog/log.sh;

log 'info' "Starting otbr-web..."
declare otbr_web_port

otbr_web_port=$OTBR_WEB_PORT

exec /usr/sbin/otbr-web -I wpan0 -d6 -p "${otbr_web_port}"
